package org.vaadin.artur;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class ReconnectConfigPanel extends VerticalLayout {
    protected Label statusLabel;
    protected TextField reconnectInterval;
    protected TextField timeoutBeforeShowingDialog;
    protected CheckBox allowInteractionWhileReconnecting;
    protected Button simulateShortDisconnect;
    protected Button simulateLongDisconnect;
    protected Button simulateBadConnection;
    protected Panel application;
    protected VerticalLayout logLayout;
    protected Button sayHelloToTheServer;
    protected Panel application2;
    protected FormLayout to;
    protected TextField toField;
    protected TextField ccField;
    protected TextField subjectField;
    protected TextArea messageField;
    protected Button sendButton;

    public ReconnectConfigPanel() {
        Design.read(this);
    }
}
